version: "3.7"

services:
# MySQL Database
  learnit-db:
    image: mariadb:latest
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    volumes:
      - learnit-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secretpassword"
      MYSQL_DATABASE: "learnit"
# API Server
  learnit-server:
    build: ./server
    ports: 
      - "8000:8000" 
    environment:
      - PORT=8000
      - JWT_SECRET=secret
      - DB_HOST=learnit-db
      - DB_PORT=3306
      - DB_NAME=learnit
      - DB_USER=root
      - DB_PASSWORD=secretpassword
    depends_on:
      - learnit-db  

# Volumes Configuration
volumes:
  learnit-data: